using System;
using Com.TheFallenGames.OSA.CustomAdapters.TableView;

namespace Com.TheFallenGames.OSA.Demos.Table
{
	/// <summary>
	/// Example demonstrating the use of a <see cref="TableAdapter{TParams, TTupleViewsHolder, THeaderTupleViewsHolder}"/>.
	/// <para>Adding data is demonstrated in <see cref="TableViewSceneEntry"/> and in the template generated by OSA Wizard</para>
	/// </summary>
	public class TableViewExample : TableAdapter<MyTableParams, MyTupleVH, MyHeaderVH>
	{
	}


	// If not needed, you can use TableParams directly as the T generic parameter in TableAdapter<T, U, V>
	[Serializable]
	public class MyTableParams : TableParams { }


	// If not needed, you can use TupleViewsHolder directly as the U generic parameter in TableAdapter<T, U, V>
	public class MyTupleVH : TupleViewsHolder { }


	// If not needed, you can use MyTupleVH or TupleViewsHolder directly as the V generic parameter in TableAdapter<T, U, V>
	public class MyHeaderVH : MyTupleVH { }
}